package com.github.jackieonway.bean.entity;

public class BiJiancha {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BI_JianCha.jianChaXiangDianId
     *
     * @mbg.generated
     */
    private Integer jianChaXiangDianId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BI_JianCha.lieBie
     *
     * @mbg.generated
     */
    private String lieBie;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BI_JianCha.jianChaYaoSu
     *
     * @mbg.generated
     */
    private String jianChaYaoSu;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BI_JianCha.jianChaXiangDian
     *
     * @mbg.generated
     */
    private String jianChaXiangDian;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BI_JianCha.jianChaBiaoZhun
     *
     * @mbg.generated
     */
    private String jianChaBiaoZhun;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BI_JianCha.shiYong
     *
     * @mbg.generated
     */
    private String shiYong;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BI_JianCha.jianChaXiangDianId
     *
     * @return the value of BI_JianCha.jianChaXiangDianId
     *
     * @mbg.generated
     */
    public Integer getJianChaXiangDianId() {
        return jianChaXiangDianId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BI_JianCha.jianChaXiangDianId
     *
     * @param jianChaXiangDianId the value for BI_JianCha.jianChaXiangDianId
     *
     * @mbg.generated
     */
    public void setJianChaXiangDianId(Integer jianChaXiangDianId) {
        this.jianChaXiangDianId = jianChaXiangDianId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BI_JianCha.lieBie
     *
     * @return the value of BI_JianCha.lieBie
     *
     * @mbg.generated
     */
    public String getLieBie() {
        return lieBie;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BI_JianCha.lieBie
     *
     * @param lieBie the value for BI_JianCha.lieBie
     *
     * @mbg.generated
     */
    public void setLieBie(String lieBie) {
        this.lieBie = lieBie == null ? null : lieBie.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BI_JianCha.jianChaYaoSu
     *
     * @return the value of BI_JianCha.jianChaYaoSu
     *
     * @mbg.generated
     */
    public String getJianChaYaoSu() {
        return jianChaYaoSu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BI_JianCha.jianChaYaoSu
     *
     * @param jianChaYaoSu the value for BI_JianCha.jianChaYaoSu
     *
     * @mbg.generated
     */
    public void setJianChaYaoSu(String jianChaYaoSu) {
        this.jianChaYaoSu = jianChaYaoSu == null ? null : jianChaYaoSu.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BI_JianCha.jianChaXiangDian
     *
     * @return the value of BI_JianCha.jianChaXiangDian
     *
     * @mbg.generated
     */
    public String getJianChaXiangDian() {
        return jianChaXiangDian;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BI_JianCha.jianChaXiangDian
     *
     * @param jianChaXiangDian the value for BI_JianCha.jianChaXiangDian
     *
     * @mbg.generated
     */
    public void setJianChaXiangDian(String jianChaXiangDian) {
        this.jianChaXiangDian = jianChaXiangDian == null ? null : jianChaXiangDian.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BI_JianCha.jianChaBiaoZhun
     *
     * @return the value of BI_JianCha.jianChaBiaoZhun
     *
     * @mbg.generated
     */
    public String getJianChaBiaoZhun() {
        return jianChaBiaoZhun;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BI_JianCha.jianChaBiaoZhun
     *
     * @param jianChaBiaoZhun the value for BI_JianCha.jianChaBiaoZhun
     *
     * @mbg.generated
     */
    public void setJianChaBiaoZhun(String jianChaBiaoZhun) {
        this.jianChaBiaoZhun = jianChaBiaoZhun == null ? null : jianChaBiaoZhun.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BI_JianCha.shiYong
     *
     * @return the value of BI_JianCha.shiYong
     *
     * @mbg.generated
     */
    public String getShiYong() {
        return shiYong;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BI_JianCha.shiYong
     *
     * @param shiYong the value for BI_JianCha.shiYong
     *
     * @mbg.generated
     */
    public void setShiYong(String shiYong) {
        this.shiYong = shiYong == null ? null : shiYong.trim();
    }
}