package com.github.jackieonway.dao.mapper;

import com.github.jackieonway.bean.entity.BiJiancha;

public interface BiJianchaMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BI_JianCha
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer jianChaXiangDianId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BI_JianCha
     *
     * @mbg.generated
     */
    int insert(BiJiancha record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BI_JianCha
     *
     * @mbg.generated
     */
    int insertSelective(BiJiancha record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BI_JianCha
     *
     * @mbg.generated
     */
    BiJiancha selectByPrimaryKey(Integer jianChaXiangDianId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BI_JianCha
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(BiJiancha record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BI_JianCha
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(BiJiancha record);
}